### ISSUE TITLE
SSO dashboard - issues found during testing

### ISSUE THREAD

**Issue by viorelaioia** [mozilla-iam/sso-dashboard#48] opened 2017-04-24 15:21 UTC
I will add here the issue that I found during testing of what we have so far in sso dashboard. 
Tested on Windows 7 (IE11, Firefox 51, Chrome), Ubuntu (Firefox 51, Chrome), Android (Firefox, Chrome), iOS (Firefox, Chrome).

- [x] All:
Hover effect is not working for search bar field
Cursor should be at the beginning (on the left side) of the search field, when focused (clicked) 

- [x] Windows 7 - IE11 only
When the search bar is focused, the placeholder disappears (before adding any search character)
[https://ibb.co/ceoPqk](https://ibb.co/ceoPqk)

- [x] Android - Chrome only: Placeholder not shown when performing click on search button
[https://ibb.co/gfwzO5](https://ibb.co/gfwzO5)

- [x] Android - Firefox only: When removing the filter after a certain app, the other apps are not loaded/shown 
[https://vimeo.com/214512305](https://vimeo.com/214512305)

- [x] iOS - Firefox, Chrome, Safari: apps remain with hover effect if they were previously clicked
[https://ibb.co/h47vwQ](https://ibb.co/h47vwQ)

CC: @comzeradd , @m-branson

**Comment by m-branson** [comment] 2017-04-24 19:32
Thanks @viorelaioia 👍

**Comment by comzeradd** [comment] 2017-04-25 11:17
> Hover effect is not working for search bar field. Cursor should be at the beginning (on the left side) of the search field, when focused (clicked)

I think that's expected behavior. The search input has `text-align: center` so that the placeholder is also aligned at the center.

> When the search bar is focused, the placeholder disappears (before adding any search character)

That's the default behavior of input placeholders on IE. Not much we can do here. We could try a prefix pseudoclass, but I'm not a fan of prefixes on css. And not fan of changing a browser default UX design.

**Comment by m-branson** [comment] 2017-04-25 16:24
> Hover effect is not working for search bar field. Cursor should be at the beginning (on the left side) of the search field, when focused (clicked)

> I think that's expected behavior. The search input has text-align: center so that the placeholder is also aligned at the center.

@comzeradd In #36 I've requested that we update the search field with `text-align: left` in the active state and focused states. `text-align: center` is merely for the placeholder text to provide visual stability to the page design. Can we achieve a `text-align: left` once a user clicks in?

**Comment by comzeradd** [comment] 2017-04-26 12:16
We can have different `text-align` on `:focus`, but that would mean that once the user clicks inside the input field the placeholder text will move to the left untill the user starts typing.

**Comment by m-branson** [comment] 2017-04-26 16:48
Okay @comzeradd, I have a proposal:

- `:focus` `text-align: center` **with** placeholder text
- Let's also utilize an `:active` state (for when a user begins typing or clicks into the field to type)
- `:active` `text-align: left` **without** placeholder text

My hope: keyboard-centric users will note the `:focus` state and begin typing; mouse-centric users will still be able to see the placeholder text and have an intuitive `:active` state experience when they click in.

Thoughts? Is this possible?

**Comment by comzeradd** [comment] 2017-04-27 18:56
Yes, that seems doable. I'll give it a try. In that case the placeholder disappears on focus. Like IE does :D

**Comment by comzeradd** [comment] 2017-04-27 18:59
> Android - Firefox only: When removing the filter after a certain app, the other apps are not loaded/shown

I'm having hard replicating this. Works both on my phone and tablet. @viorelaioia is this on FF53?

**Comment by comzeradd** [comment] 2017-04-27 19:41
@m-branson this is now on stage.

**Comment by m-branson** [comment] 2017-04-27 19:54
@comzeradd that's looking great! Feels pretty intuitive to me, would love to know what @viorelaioia thinks. :)

One last thing visually, can we visually center the placeholder text and align styles as we see here (apologies for not catching earlier!):

![search-placeholder-position-style](https://cloud.githubusercontent.com/assets/18686986/25501758/a7455e9e-2b48-11e7-922c-72778e0c91ce.png)

**Comment by m-branson** [comment] 2017-04-27 21:48
@comzeradd realizing the search bar hover state (cursor) is not in place, I believe @viorelaioia called it out here as well:

> All:
Hover effect is not working for search bar field

This is the UI for it (orange borders with placeholder text still in place):

<img width="554" alt="search-bar-hover" src="https://cloud.githubusercontent.com/assets/18686986/25505825/70dc8a16-2b58-11e7-9ba8-1d670529d1d9.png">

**Comment by comzeradd** [comment] 2017-04-28 09:27
Yes, you are right. For some reason I though the highlight on search only takes place on focus. I'll push a fix.

**Comment by comzeradd** [comment] 2017-04-28 10:33
Unfortunately the `::placeholder` selector has limited options support on all browsers (eg. no `text-align`). But with some js magic and paddings I think I managed to put the placehodler to look visually on center. But not all browsers render fonts and placeholder texts the same way so it's hard to have pixel accuracy.

**Comment by viorelaioia** [comment] 2017-04-28 10:58
> Android - Firefox only: When removing the filter after a certain app, the other apps are not loaded/shown
I'm having hard replicating this. Works both on my phone and tablet. @viorelaioia is this on FF53?

I tried again and it looks like the device I used for testing had an older version of Firefox (48).
I installed the latest version and I was not able to reproduce the issue anymore. Sorry about that!

**Comment by comzeradd** [comment] 2017-04-28 11:37
> iOS - Firefox, Chrome, Safari: apps remain with hover effect if they were previously clicked

@viorelaioia Can you also check that one? We now defaulted on opening apps on a new tab.

**Comment by viorelaioia** [comment] 2017-04-28 13:10
I did a check and if I go back to the dashboard tab only the last clicked app has the orange border. Not sure if that is expected behavior or not.

**Comment by comzeradd** [comment] 2017-04-28 13:12
Yes, that's expected :) Thanks

**Comment by comzeradd** [comment] 2017-04-28 19:15
All issues are now fixed, due to d98a24d173a82427e19e312888d0f203b289c49d and 26372bae18f2e0df75ee1b39c5259a814e32a844

Hiding the placeholder on focus is now expected behavior in order to manipulate the text alignment.

**Closed by comzeradd** 2017-04-28 19:15 UTC
Labels: :IN PROGRESS:, :RELEASE 1.0:, :SPRINT 6:, [AUTHO DASHBOARD]
